name: Jest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]

    services:
      postgres:
        image: postgres:latest
        ports: 
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTFRES_PASSWORD: testpassword
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    env: 
      DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test
